### ISSUE TITLE
Batch file missing variable COM port

### ISSUE THREAD

**Issue by mike-perks** [PPUC/ZeDMD#21]
I see we jumped from 2.1 to now 3.0 :)

For the last few releases, the COM port is hard-coded in the batch file. I'm not sure why this was taken out because not every ZeDMD board is connected to COM3.

Strictly speaking the compressed files are compressed with the 7z algorithm and they cannot be unzipped with the standard unzip programs. It needs 7zip which understands both formats. I recommend rezipping in the compatible format rather than renaming the extension to .7z

**Comment by mkalkbrenner** [comment]
We're working on libzedmd and our own flashing program.
