### ISSUE TITLE
zedmd various problems

### ISSUE THREAD

**Issue by Pinbalbilly** [PPUC/ZeDMD#39]
Hi, I don't know if this is the right place to report bugs I'm having with zedmd.  I have Vpinmame 3.6, frezzy 2.2.0 beta2, in zedmd HD, I find the following errors: -sega tables Baywatch, maverick, Frankenstein, the dmd image is not understandable, everything is mixed up, it is impossible to use it.  - tables data east hook, Batman, checkpoint, turtles, the dmd comes out double, duplicate, attached photos.  Any help to fix the problem?

Sega

![Screenshot_2023-07-13-00-18-21-497_com google android apps photos-edit](https://github.com/PPUC/ZeDMD/assets/136266013/f1ce4778-12a0-45d4-8c43-3f33697cf824)

Data East

![IMG_20230714_162706](https://github.com/PPUC/ZeDMD/assets/136266013/7c5cb53a-adfc-42fb-ad6a-149be31fd535)

**Comment by mkalkbrenner** [comment]
I just tested Baywatch and Star Trek with ZeDMD HD, both work perfectly well with DMD Ext 2.1.2.

But I'll try the dev version DMD Ext now.

**Comment by Pinbalbilly** [comment]
> 

ok, I wait for news, thanks

**Comment by mkalkbrenner** [comment]
Will be fixed by https://github.com/freezy/dmd-extensions/pull/450
