### ISSUE TITLE
Updating to 3.5.0 doesn't work

### ISSUE THREAD

**Issue by gustavoalara** [PPUC/ZeDMD#50]
Hi,

I'm trying to update my 256x64 ZeDMD to 3.5.0 release without successful. The process looks like is correct using the ZeDMD update tool or even via command line with the esp32tool, but when the process finished the ESP32 appears as a COM3 device but not a ZeDMD device (and the leds blinks constantly, doesn't matter if disconnect and connect again the ESP32 or reset it). If I apply a rollup and back to 3.4.1 release, everything works correctly.

I've tried even with wifi or 128x32 versions

**Comment by mkalkbrenner** [comment]
I found the issue with the image build and the new espressif version. The assets of the v3.5.0 release have been replaced by new zip files which should work now.
